settings:
  variables:
    entity_tablet: switch.galaxy_tab_a_screensaver
    entity_browser_mod: media_player.browser_dd239c79_406b9d77
    translate_unknown: Unbekannt
    translate_idle: Inaktiv
    translate_home: Ja
    translate_not_home: Nein
    translate_available: Verfügbar
    translate_no_updates: Keine Updates
    translate_update_available: Update verfügbar
    translate_updates_available: Updates verfügbar
