settings:
  variables:
    entity_tablet: switch.galaxy_tab_a_screensaver
    entity_browser_mod: media_player.tablet
    translate_unknown: Unbekannt
    translate_idle: Inaktiv
    translate_home: Ja
    translate_not_home: Nein
    translate_available: Verf端gbar
    translate_no_updates: Keine Updates verf端gbar
    translate_update_available: Update verf端gbar
    translate_updates_available: Updates verf端gbar
