- id: '1637874267399'
  alias: System - Set Custom Theme at Startup
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: frontend.set_theme
    data:
      name: tablet
  initial_state: true
  mode: single
- id: '1652002480816'
  alias: Benachrichtigung Wassersensor Küche
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.wassersensor_kuche
    from: 'off'
    to: 'on'
  condition: []
  action:
  - device_id: edd104c9d17926e2207866013b183e1e
    domain: mobile_app
    type: notify
    message: Wasser in der Küche!
  - service: media_player.play_media
    target:
      entity_id: media_player.wohnzimmer
    data:
      media_content_id: media-source://tts/google_translate?message=Wasser+in+der+K%C3%BCche
      media_content_type: provider
    metadata:
      title: Wasser in der Küche
      thumbnail: https://brands.home-assistant.io/_/google_translate/logo.png
      media_class: app
      children_media_class:
      navigateIds:
      - {}
      - media_content_type: app
        media_content_id: media-source://tts
      - media_content_type: provider
        media_content_id: media-source://tts/google_translate?message=Wasser+in+der+K%C3%BCche
  mode: single
