# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

# group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


device_tracker:
  - platform: ping
    hosts:
      laptop_tim: !secret laptop_tim
      handy_clarissa: !secret handy_clarissa
      handy_tim: !secret handy_tim
      uhr_tim: !secret uhr_tim

wake_on_lan:

switch:
  # - platform: wake_on_lan
  #   mac: !secret mac_pc_tim
  #   name: WOL PC Tim
  - platform: wake_on_lan
    mac: !secret mac_drucker
    name: WOL Drucker

# python_script:

# browser_mod:
#   prefix: browser_

logger:
  default: info
  logs:
    homeassistant.components.yamaha: critical
    custom_components.my_integration: critical

waste_collection_schedule:
  sources:
    name: ics
    args:
      url: "https://waste.awb-landkreis-karlsruhe.de/WasteManagementKarlsruheHaushalteBlank/WasteManagementServiceServlet?ApplicationName=Calendar&SubmitAction=sync&StandortID=707245001&AboID=23908"
    customize:
      - type: Mobile Schadstoffsammlung
        alias: Schadstoffe
      - type: Biobehaelter
        alias: Bio
      - type: Restabfallbehaelter
        alias: Restabfall
      - type: Wertstoffbehaelter
        alias: Wertstoff

media_player:
  - platform: onkyo
    host: !secret onkyo_receiver
    name: receiver

homeassistant:
  name: Startseite
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Berlin
  currency: EUR
  packages: !include_dir_named packages
  customize_domain:
    automation:
      initial_state: true
  allowlist_external_dirs:
    - /config
  legacy_templates: false

frontend: !include themes.yaml
template: !include sidebar.yaml

lovelace:
  mode: yaml #use ui-lovelace.yaml
  resources: #hacs
    [
      { url: /hacsfiles/apexcharts-card/apexcharts-card.js,                         type: module },
      { url: /hacsfiles/bar-card/bar-card.js,                                       type: module },
      { url: /hacsfiles/button-card/button-card.js,                                 type: module },
      { url: /hacsfiles/custom-icons/custom-icons.js,                               type: module },
      { url: /hacsfiles/kiosk-mode/kiosk-mode.js,                                   type: module },
      { url: /hacsfiles/lovelace-layout-card/layout-card.js,                        type: module },
      { url: /hacsfiles/lovelace-more-info-card/more-info-card.js,                  type: module },
      { url: /hacsfiles/lovelace-mushroom/mushroom.js,                              type: module },
      { url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js,            type: module },
      { url: /hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js,  type: module },
      { url: /hacsfiles/swipe-card/swipe-card.js,                                   type: module },

      { url: '/local/marked.min.js?v=4.0.18',                                       type: module },
      { url: '/local/vanilla-tilt.min.js?v=1.7.2',                                  type: module },
      { url: '/local/fonts.css?v=2.1',                                              type: css },


      { url: /hacsfiles/lovelace-auto-entities/auto-entities.js, type: module },
      { url: '/local/browser_mod_icon.js?v=0.3',                                    type: module },
      {
        url: /hacsfiles/seventeen-track-card/seventeen-track-card.js,
        type: module,
      },
      {
        url: "/hacsfiles/upcoming-media-card/upcoming-media-card.js",
        type: module,
      },
      { url: "/hacsfiles/rmv-card/rmv-card.js?v=0", type: module },
      { url: "/hacsfiles/lovelace-fan-xiaomi/fan-xiaomi.js", type: module },
      { url: "/hacsfiles/custom-brand-icons/custom-brand-icons.js", type: module }
    ]

recorder:
  purge_keep_days: 2
  commit_interval: 30
  exclude:
    domains:
      - device_tracker
      - media_player
      - uptime
      - time_date
      - worldclock
      - button
      - automation
      - calendar
      - input_select
      - remote
      - switch
      - update
    entity_globs:
      - sensor.clock*
      - sensor.date*
      - sensor.glances*
      - sensor.load_*m
      - sensor.time*
      - sensor.uptime*
      - sensor.hass*
      - sensor.next*
      - sensor.*version
      - weather.*
      - sensor.browser_*
      - light.browser_*
      - media_player.browser_*
      - binary_sensor.arris*
      - sensor.arris*
      - sensor.template_*
      # - sensor.ds216plus*
    entities:
      # - camera.front_door
      - sensor.home_assistant_v2_db
      - sensor.memory_free
      - sensor.memory_use
      - sensor.memory_use_percent
      - sensor.processor_use
      - weather.openweathermap
      - sun.sun
      - sensor.template_imac_uptime
      - sensor.template_sidebar
      - camera.xiaomi_cloud_map_extractor
      - sensor.home_assistant_log

# fan:
#   - platform: xiaomi_miio_fan
#     name: Xiaomi Smart Fan
#     host: !secret xiaomi_fan_host
#     token: !secret xiaomi_fan_token
