# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_host
    token: !secret xiaomi_token
    username: !secret xiaomi_username
    password: !secret xiaomi_password
    country: "de"
    colors:
      color_robo: [224, 224, 224]
      color_charger: [27, 117, 27]
      color_path: [30, 80, 113]
      color_goto_path: [30, 80, 113]
      color_map_wall_v2: [30, 30, 30]
      color_obstacle: [30, 30, 30]
      color_virtual_walls: [255, 0, 0, 60]
      color_no_go_zones_outline: [255, 0, 0, 60]
      color_no_go_zones: [255, 0, 0, 28]
      color_scan: [0, 0, 0, 0]
      color_map_inside: [0, 0, 0, 0]
      color_map_outside: [0, 0, 0, 0]
      color_grey_wall: [0, 0, 0, 0]
      color_map_wall: [0, 0, 0, 0]
    room_colors:
      1: [42, 46, 48]
      2: [42, 46, 48]
      3: [42, 46, 48]
      4: [42, 46, 48]
      5: [42, 46, 48]
    draw: ["all"]
    map_transformation:
      scale: 2
      trim:
        top: 16
        right: 22
        bottom: 25
        left: 21
    sizes:
      charger_radius: 10
      vacuum_radius: 10
    attributes:
      - calibration_points

device_tracker:
  - platform: ping
    hosts:
      laptop_tim: !secret laptop_tim
      handy_clarissa: !secret handy_clarissa
      handy_tim: !secret handy_tim
      uhr_tim: !secret uhr_tim
      pc_tim: !secret pc_tim

wake_on_lan:

switch:
  - platform: wake_on_lan
    mac: !secret mac_pc_tim
    name: WOL PC Tim
  - platform: wake_on_lan
    mac: !secret mac_drucker
    name: WOL Drucker

# python_script:

browser_mod:
  prefix: browser_

logger:
  default: info
  logs:
    homeassistant.components.yamaha: critical
    custom_components.my_integration: critical

waste_collection_schedule:
  sources:
    name: ics
    args:
      url: "https://waste.awb-landkreis-karlsruhe.de/WasteManagementKarlsruheHaushalteBlank/WasteManagementServiceServlet?ApplicationName=Calendar&SubmitAction=sync&StandortID=707245001&AboID=23908"
    customize:
      - type: Mobile Schadstoffsammlung
        alias: Schadstoffe
      - type: Biobehaelter
        alias: Bio
      - type: Restabfallbehaelter
        alias: Restabfall
      - type: Wertstoffbehaelter
        alias: Wertstoff

bring_shopping_list:
  lists:
    - id: !secret bring_list_id
      name: Zuhause
      locale: de-DE

media_player:
  - platform: onkyo
    host: !secret onkyo_receiver
    name: receiver

homeassistant:
  name: Startseite
  packages: !include_dir_named include #theme
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  temperature_unit: C
<<<<<<< HEAD
  time_zone: Europe/Berlin
  currency: EUR
=======
  time_zone: Europe/Stockholm
  currency: SEK
  packages: !include_dir_named packages
  customize_domain:
    automation:
      initial_state: true
>>>>>>> upstream/master
  allowlist_external_dirs:
    - /config
  legacy_templates: false

frontend: !include themes.yaml
template: !include sidebar.yaml

lovelace:
<<<<<<< HEAD
  mode: yaml #use ui-lovelace.yaml
  resources: #hacs
    [
      { url: /hacsfiles/apexcharts-card/apexcharts-card.js, type: module },
      { url: /hacsfiles/bar-card/bar-card.js, type: module },
      { url: /hacsfiles/button-card/button-card.js, type: module },
      { url: /hacsfiles/kiosk-mode/kiosk-mode.js, type: module },
      { url: /hacsfiles/light-entity-card/light-entity-card.js, type: module },
      { url: /hacsfiles/light-popup-card/light-popup-card.js, type: module },
      {
        url: "/hacsfiles/mini-graph-card/mini-graph-card-bundle.js?v=0.10.0",
        type: module,
      },
      { url: /hacsfiles/lovelace-card-mod/card-mod.js, type: module },
      { url: /hacsfiles/lovelace-layout-card/layout-card.js, type: module },
      {
        url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js,
        type: module,
      },
      {
        url: /hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js,
        type: module,
      },
      { url: /hacsfiles/swipe-card/swipe-card.js, type: module },
      { url: /hacsfiles/lovelace-auto-entities/auto-entities.js, type: module },
      { url: "/local/calendar-card.js?v=3.109.1", type: module },
      { url: "/local/custom_icons.js?v=28082021", type: module },
      { url: "/local/marked.min.js?v=4.0.12", type: module },
      { url: "/local/vanilla-tilt.min.js?v=1.7.2", type: module },
      { url: /local/font.css, type: css },
      { url: /browser_mod.js, type: module },
      {
        url: /hacsfiles/seventeen-track-card/seventeen-track-card.js,
        type: module,
      },
      {
        url: "/hacsfiles/upcoming-media-card/upcoming-media-card.js",
        type: module,
      },
      { url: "/hacsfiles/rmv-card/rmv-card.js?v=0", type: module },
      { url: "/hacsfiles/lovelace-fan-xiaomi/fan-xiaomi.js", type: module },
    ]

recorder:
  purge_keep_days: 2
  commit_interval: 30
  exclude:
    domains:
      - device_tracker
      - media_player
      - uptime
      - time_date
      - worldclock
      - button
      - automation
      - calendar
      - input_select
      - remote
      - switch
      - update
    entity_globs:
      - sensor.clock*
      - sensor.date*
      - sensor.glances*
      - sensor.load_*m
      - sensor.time*
      - sensor.uptime*
      - sensor.hass*
      - sensor.next*
      - sensor.*version
      - weather.*
      - sensor.browser_*
      - light.browser_*
      - media_player.browser_*
      - binary_sensor.arris*
      - sensor.arris*
      - sensor.template_*
      # - sensor.ds216plus*
    entities:
      # - camera.front_door
      - sensor.home_assistant_v2_db
      - sensor.memory_free
      - sensor.memory_use
      - sensor.memory_use_percent
      - sensor.processor_use
      - weather.openweathermap
      - sun.sun
      - sensor.template_imac_uptime
      - sensor.template_sidebar
      - camera.xiaomi_cloud_map_extractor
      - sensor.home_assistant_log

person:
  # - name: Tim
  #   id: tim
  #   device_trackers:
  #     - device_tracker.handy_tim
  #     - device_tracker.uhr_tim

  - name: Clarissa
    id: clarissa
    device_trackers:
      - device_tracker.handy_clarissa

fan:
  - platform: xiaomi_miio_fan
    name: Xiaomi Smart Fan
    host: !secret xiaomi_fan_host
    token: !secret xiaomi_fan_token
=======
  mode: yaml
  resources:
    [
      { url: /hacsfiles/apexcharts-card/apexcharts-card.js,                         type: module },
      { url: /hacsfiles/bar-card/bar-card.js,                                       type: module },
      { url: /hacsfiles/button-card/button-card.js,                                 type: module },
      { url: /hacsfiles/custom-icons/custom-icons.js,                               type: module },
      { url: /hacsfiles/kiosk-mode/kiosk-mode.js,                                   type: module },
      { url: /hacsfiles/lovelace-layout-card/layout-card.js,                        type: module },
      { url: /hacsfiles/lovelace-more-info-card/more-info-card.js,                  type: module },
      { url: /hacsfiles/lovelace-mushroom/mushroom.js,                              type: module },
      { url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js,            type: module },
      { url: /hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js,  type: module },
      { url: /hacsfiles/swipe-card/swipe-card.js,                                   type: module },

      { url: '/local/marked.min.js?v=4.0.18',                                       type: module },
      { url: '/local/vanilla-tilt.min.js?v=1.7.2',                                  type: module },
      { url: '/local/fonts.css?v=2.1',                                              type: css }
    ]

recorder:
  db_url: !secret recorder_db_url
  exclude:
    entity_globs:
      - sensor.browser_*

logger:
  default: warning
  logs:
    homeassistant.components.websocket_api: fatal
    custom_components.monitor_docker.helpers: fatal

sensor:
  - platform: time_date
    display_options:
      - time
      - date
>>>>>>> upstream/master
