homeassistant:
  ####################################################
  #                                                  #
  #                    CUSTOMIZE                     #
  #                                                  #
  ####################################################

  customize_domain:
    automation:
      initial_state: true

  customize:
    #light
    light.group_belysning:
      friendly_name: Belysning
      icon: mdi:lamp
    light.dator:
      friendly_name: Datorlampa
    light.group_taklampor:
      friendly_name: Taklampor
    light.group_sanglampor:
      friendly_name: Sänglampor
      icon: mdi:floor-lamp
    light.group_badrum:
      friendly_name: Badrum
    light.group_hall:
      friendly_name: Hallampor

    #esphome/energy
    sensor.gosund_ac_daily_energy:
      friendly_name: Electrolux ChillFlex Pro Gold

    #media_player
    media_player.sony_bravia_tv:
      friendly_name: Tv
      device_class: tv
    media_player.samsung_tv:
      friendly_name: "Tv\u00B2"
      device_class: tv
    media_player.spotify:
      friendly_name: Spotify
    media_player.kok:
      friendly_name: Google Nest Mini

    #binary_sensor
    binary_sensor.sensor_hall_motion:
      friendly_name: hallen
    binary_sensor.sensor_badrum_motion:
      friendly_name: badrummet
    binary_sensor.sensor_garderob_motion:
      friendly_name: klädkammaren
    binary_sensor.wemo_motion:
      friendly_name: vardagsrummet

    #battery
    sensor.switchbot_battery:
      friendly_name: Switchbot
      device_class: battery
    sensor.dimmer_badrum_battery_level:
      friendly_name: Dimmer Badrum
    sensor.dimmer_sovrum_battery_level:
      friendly_name: Dimmer Sovrum
    sensor.sensor_hall_battery:
      friendly_name: Sensor Hall
    sensor.sensor_garderob_battery:
      friendly_name: Sensor Garderob
    sensor.sensor_badrum_battery:
      friendly_name: Sensor Badrum

    #fan
    fan.studio:
      icon: custom:pedestal-fan

    # template.yaml
    select.vacuum_speed:
      friendly_name: Rengöringsläge
      icon: mdi:format-list-bulleted
    select.hdmi_bravia:
      friendly_name: Källa
      icon: custom:hdmi-source
    select.hdmi_samsung:
      friendly_name: Källa
      icon: custom:hdmi-source

    #vardagsrum_balkong.yaml
    switch.deltaco_sh_p01:
      friendly_name: Balkong
      icon: mdi:lightbulb-variant
    automation.balcony:
      friendly_name: Tänd ljusslinga med rörelsedetektor

    #sidebar_vacuum.yaml
    vacuum.robi:
      friendly_name: Roborock S5
      icon: custom:roborock-vacuum
    sensor.robi_last_clean_end:
      friendly_name: Senast städat
      icon: mdi:calendar-clock

    #sidebar_information.yaml
    switch.galaxy_tab_a_screensaver:
      friendly_name: Skärmsläckare
      icon: mdi:power-sleep
    light.galaxy_tab_a_screen:
      friendly_name: Display
      icon: mdi:tablet
    binary_sensor.galaxy_tab_a_plugged_in:
      friendly_name: Strömtillförsel
      icon: mdi:power-plug
    sensor.galaxy_tab_a_last_app_start:
      friendly_name: Senast omstart
      icon: mdi:update
    sensor.galaxy_tab_a_battery_level:
      friendly_name: Batteri
    sensor.ds216plus_volume_1_average_disk_temp:
      friendly_name: Disktemperatur
    sensor.processor_use_percent:
      icon: mdi:chip

    # vardagsrum_tv.yaml
    automation.tv_on_lights:
      friendly_name: Tänd Tv-lampa

    # studio_dator.yaml
    sensor.imac_cpu:
      friendly_name: Processor
      icon: mdi:chip
    sensor.imac_mem:
      friendly_name: Minne
      icon: mdi:memory
    automation.macos_notification_motion_hall:
      friendly_name: Mottag notiser
      icon: mdi:bell
    sensor.imac_uptime:
      friendly_name: Senaste omstart
      icon: mdi:update
      device_class: timestamp
    sensor.mattias_imac_storage:
      friendly_name: Macintosh HD
      icon: custom:imac-ssd

    # studio_monitorer.yaml
    switch.gosund_monitors_switch:
      friendly_name: Monitorer
      icon: custom:studio-monitor
    automation.turn_off_monitors:
      friendly_name: Stäng av när dator stängs av
      icon: mdi:power
    automation.eq_calibration:
      friendly_name: Automatisk kalibrationsprofil
      icon: custom:eq-calibrate

    #person
    person.matte:
      entity_picture: /local/mattias.png
    sensor.mattias_weight:
      unit_of_measurement: kg
    device_tracker.mattias_iphone_ios:
      entity_picture: /local/device_tracker.svg
    person.sanja:
      entity_picture: /local/sanja.png

    #sort
    sensor.rpi_cpu:
      friendly_name: Processor
      icon: mdi:chip
    sensor.rpi_mem:
      friendly_name: Minne
      icon: mdi:memory
    sensor.rpi_sd:
      friendly_name: SD-kort
      icon: mdi:micro-sd
    sensor.rpi_uptime:
      friendly_name: Senaste omstart
      icon: mdi:update
      device_class: timestamp
