sensor:
  - platform: time_date
    display_options:
      - time
      - date

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot
    scan_interval: 120

  # - platform: darksky
  #   api_key: !secret darksky_api_key
  #   language: sv
  #   monitored_conditions:
  #     - temperature
  #     - apparent_temperature
  #     - precip_probability
  # - platform: plex_recently_added
  #   token: !secret plex_token
  #   host: !secret plex_host
  #   port: !secret plex_port
  #   max: 1
  #   img_dir: /
  #   image_resolution: 900
  - platform: waste_collection_schedule
    name: Müllabfuhr
    value_template: >
      {{ value.daysTo }}

    ####################################################
    #                                                  #
    #                   COMMAND LINE                   #
    #                                                  #
    ####################################################

  # - platform: command_line
  #   name: imac_cpu
  #   command: !secret imac_cpu
  #   unit_of_measurement: '%'
  #   value_template: >
  #     {{ (100 - value[:-1] | float(default=0)) | round(1) }}
  #   scan_interval: 86400

  # - platform: command_line
  #   name: imac_mem
  #   command: !secret imac_mem
  #   unit_of_measurement: '%'
  #   scan_interval: 86400

  # - platform: command_line
  #   name: imac_uptime
  #   command: !secret imac_uptime
  #   value_template: >
  #     {% set timestamp = value[:-1] | int(default=0) %}
  #     {% set year = 86400 * 365 %}
  #     {{ timestamp | timestamp_local if (as_timestamp(now()) - timestamp) < year else None}}
  #   scan_interval: 86400

  # - platform: command_line
  #   name: imac_ip
  #   command: !secret imac_ip
  #   scan_interval: 86400

  # - platform: command_line
  #   name: monitors_volume
  #   command: !secret monitors_update_volume
  #   scan_interval: 86400

  # - platform: command_line
  #   name: rpi_cpu
  #   command: !secret rpi_cpu
  #   unit_of_measurement: '%'
  #   scan_interval: 300

  # - platform: command_line
  #   name: rpi_mem
  #   command: !secret rpi_mem
  #   unit_of_measurement: '%'
  #   value_template: >
  #     {{ value | round(1) }}
  #   scan_interval: 300

  # - platform: command_line
  #   name: rpi_sd
  #   command: !secret rpi_sd
  #   unit_of_measurement: '%'
  #   value_template: >
  #     {{ value[:-1] }}
  #   scan_interval: 300

  # - platform: command_line
  #   name: rpi_uptime
  #   command: !secret rpi_uptime
  #   value_template: >
  #     {{ value | replace(' ', 'T') }}
  #   scan_interval: 300

  # - platform: command_line
  #   name: udm_unifios
  #   command: !secret udm_unifios
  #   value_template: |-
  #     {% set json = value_json.data[0] %}
  #     {{ json["system-stats"].cpu }}|
  #     {{ json.temperatures[1].value | round(1) }}|
  #     {{ json["system-stats"].mem }}|
  #     {{ ((json.storage[1].used / json.storage[1].size) * 100) | round(1) }}|
  #     {{ json.internet }}|
  #     {{ json.startup_timestamp | timestamp_local }}|
  #     {{ json.displayable_version }}|
  #     {{ json.upgradable }}
  #   scan_interval: 120

  # - platform: command_line
  #   name: kemper_version
  #   command: !secret kemper_version
  #   value_template: >
  #     {{ value_json.profiler_installed == value_json.profiler_latest and
  #     value_json.rigmanager_latest == value_json.rigmanager_installed }}
  #   json_attributes:
  #     - profiler_latest
  #     - profiler_installed
  #     - rigmanager_latest
  #     - rigmanager_installed
  #   scan_interval: 86400

  # - platform: command_line
  #   name: playactor_version_installed
  #   command: !secret playactor_version_installed
  #   value_template: >
  #     {{ value.split(' ')[1].split('v')[1] }}
  #   scan_interval: 86400

  - platform: command_line
    name: hacs_installed
    command: |-
      python3 << EOF
      import os, json
      installed = {"repositories": []}
      path = "/config/.storage/hacs/"
      for file in os.listdir(path):
          name, ext = os.path.splitext(file)
          if ext == ".hacs":
              hacs_file = path + file
              with open(hacs_file, "r") as file:
                  dict = json.load(file)
                  name = dict["data"]["full_name"]
                  installed["repositories"] += [name]
                  file.close()
      print(json.dumps(installed))
      EOF
    value_template: >
      {{ value_json.repositories | count }}
    json_attributes:
      - repositories
    scan_interval: 86400

  ####################################################
  #                                                  #
  #                   RMV                            #
  #                                                  #
  ####################################################

  - platform: rmvtransport
    next_departure:
      - name: bad_schoenborn_kronau
        station: 8004032

  ####################################################
  #                                                  #
  #                   17track                        #
  #                                                  #
  ####################################################

  - platform: seventeentrack
    username: !secret seventeentrack_username
    password: !secret seventeentrack_password
