sensor:
  - platform: time_date
    display_options:
      - time
      - date

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot
    scan_interval: 120

  ####################################################
  #                                                  #
  #                   MÜLL                           #
  #                                                  #
  ####################################################

  - platform: waste_collection_schedule
    name: Müllabfuhr
    value_template: '{{value.types|join(", ")}}|{{value.daysTo}}|{{value.date.strftime("%d.%m.%Y")}}|{{value.date.strftime("%a")}}'

  ####################################################
  #                                                  #
  #                   HACS                           #
  #                                                  #
  ####################################################

  - platform: command_line
    name: hacs_installed
    command: |-
      python3 << EOF
      import os, json
      installed = {"repositories": []}
      path = "/config/.storage/hacs/"
      for file in os.listdir(path):
          name, ext = os.path.splitext(file)
          if ext == ".hacs":
              hacs_file = path + file
              with open(hacs_file, "r") as file:
                  dict = json.load(file)
                  name = dict["data"]["full_name"]
                  installed["repositories"] += [name]
                  file.close()
      print(json.dumps(installed))
      EOF
    value_template: >
      {{ value_json.repositories | count }}
    json_attributes:
      - repositories
    scan_interval: 86400

  ####################################################
  #                                                  #
  #                   RMV                            #
  #                                                  #
  ####################################################

  - platform: rmvtransport
    next_departure:
      - name: bad_schoenborn_kronau
        station: 8004032

  ####################################################
  #                                                  #
  #                   17track                        #
  #                                                  #
  ####################################################

  - platform: seventeentrack
    username: !secret seventeentrack_username
    password: !secret seventeentrack_password
