homeassistant:
  customize:
    vacuum.robi:
      icon: cil:roborock-vacuum
    sensor.robi_last_clean_end:
      friendly_name: Letzte Reinigung
      icon: mdi:calendar-clock

template:
  - sensor:
      - unique_id: vacuum_filter
        state: >
          {% set entity_id = 'sensor.robi_filter_left' %}
          {{ (states(entity_id) | int(default=0) / 5400) | int(default=0) }}
        attributes:
          friendly_name: Filter
          icon: cil:roborock-filter
          unit_of_measurement: "%"

      - unique_id: vacuum_mainbrush
        state: >
          {% set entity_id = 'sensor.robi_main_brush_left' %}
          {{ (states(entity_id) | int(default=0) / 10800) | int(default=0) }}
        attributes:
          friendly_name: Hauptbürste
          icon: cil:roborock-mainbrush
          unit_of_measurement: "%"

      - unique_id: vacuum_sensors
        state: >
          {% set entity_id = 'sensor.robi_sensor_dirty_left' %}
          {{ (states(entity_id) | int(default=0) / 1080) | int(default=0) }}
        attributes:
          friendly_name: Sensoren
          icon: cil:roborock-sensor
          unit_of_measurement: "%"

      - unique_id: vacuum_sidebrush
        state: >
          {% set entity_id = 'sensor.robi_side_brush_left' %}
          {{ (states(entity_id) | int(default=0) / 7200) | int(default=0) }}
        attributes:
          friendly_name: Seitenbürste
          icon: cil:roborock-sidebrush
          unit_of_measurement: "%"

      - unique_id: last_clean_duration_min
        icon: mdi:timer-sand
        state: >
          {% set duration = states('sensor.robi_last_clean_duration') | int(0) %}
          {%- set TIME_MAP = {
                        'w': (duration / 604800) % 604800,
                        'd': (duration / 86400) % 7,
                        'h': (duration / 3600) % 24,
                        'm': (duration / 60) % 60,
                        's': (duration % 60)
                    }
          -%}
          {% if (TIME_MAP.h|int(0) > 0) %}
          {{TIME_MAP.h|int(0)}} Stunde, {{TIME_MAP.m|int(0)}} Minuten
          {% else %}
          {{TIME_MAP.m|int(0)}} Minuten
          {% endif %}
        attributes:
          friendly_name: Dauer
# automation:
#   - alias: vacuum_empty_bin
#     id: "5443599527378"
#     variables:
#       vacuum: vacuum.robi
#     trigger:
#       platform: state
#       entity_id: sensor.robi_total_clean_count
#     condition: >
#       {{ not is_state(vacuum, 'docked') }}
#     action:
#       - delay:
#           seconds: 2
#       - if: >
#           {{ is_state(vacuum, 'returning') }}
#         then:
#           - service: vacuum.pause
#             target:
#               entity_id: >
#                 {{ vacuum }}
#           - delay:
#               seconds: 2
#           - service: xiaomi_miio.vacuum_goto
#             target:
#               entity_id: >
#                 {{ vacuum }}
#             data:
#               x_coord: 16821
#               y_coord: 23105

camera:
  - platform: xiaomi_cloud_map_extractor
    host: !secret xiaomi_host
    token: !secret xiaomi_token
    username: !secret xiaomi_username
    password: !secret xiaomi_password
    country: "de"
    colors:
      color_robo: [224, 224, 224]
      color_charger: [27, 117, 27]
      color_path: [30, 80, 113]
      color_goto_path: [30, 80, 113]
      color_map_wall_v2: [30, 30, 30]
      color_obstacle: [30, 30, 30]
      color_virtual_walls: [255, 0, 0, 60]
      color_no_go_zones_outline: [255, 0, 0, 60]
      color_no_go_zones: [255, 0, 0, 28]
      color_scan: [0, 0, 0, 0]
      color_map_inside: [0, 0, 0, 0]
      color_map_outside: [0, 0, 0, 0]
      color_grey_wall: [0, 0, 0, 0]
      color_map_wall: [0, 0, 0, 0]
    room_colors:
      1: [42, 46, 48]
      2: [42, 46, 48]
      3: [42, 46, 48]
      4: [42, 46, 48]
      5: [42, 46, 48]
    draw: ["all"]
    map_transformation:
      scale: 2
      trim:
        top: 16
        right: 22
        bottom: 25
        left: 21
    sizes:
      charger_radius: 10
      vacuum_radius: 10
    attributes:
      - calibration_points
    scan_interval: 10
